// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.
package graph

import (
	"context"

	"github.com/benchmark/go-gqlgen/graph/model"
)

type Config struct {
	Resolvers ResolverRoot
}

type ResolverRoot interface {
	Query() QueryResolver
	Mutation() MutationResolver
	User() UserResolver
	Post() PostResolver
	Comment() CommentResolver
}

type QueryResolver interface {
	Ping(ctx context.Context) (string, error)
	User(ctx context.Context, id string) (*model.User, error)
	Users(ctx context.Context, limit *int) ([]*model.User, error)
	Post(ctx context.Context, id string) (*model.Post, error)
	Posts(ctx context.Context, limit *int) ([]*model.Post, error)
	Comment(ctx context.Context, id string) (*model.Comment, error)
	Comments(ctx context.Context, limit *int) ([]*model.Comment, error)
}

type MutationResolver interface {
	UpdateUser(ctx context.Context, id string, firstName *string, lastName *string, bio *string) (*model.User, error)
}

type UserResolver interface {
	Posts(ctx context.Context, obj *model.User, limit *int) ([]*model.Post, error)
	FollowerCount(ctx context.Context, obj *model.User) (int, error)
}

type PostResolver interface {
	Author(ctx context.Context, obj *model.Post) (*model.User, error)
	Comments(ctx context.Context, obj *model.Post, limit *int) ([]*model.Comment, error)
}

type CommentResolver interface {
	Author(ctx context.Context, obj *model.Comment) (*model.User, error)
	Post(ctx context.Context, obj *model.Comment) (*model.Post, error)
}

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot and Directives.
func NewExecutableSchema(cfg Config) interface{} {
	return cfg
}
