// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID      string `json:"id"`
	Content string `json:"content"`
	Author  *User  `json:"author,omitempty"`
	Post    *Post  `json:"post,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	Content   *string    `json:"content,omitempty"`
	Author    *User      `json:"author"`
	Comments  []*Comment `json:"comments"`
	CreatedAt string     `json:"createdAt"`
}

type Query struct {
}

type User struct {
	ID        string  `json:"id"`
	Username  string  `json:"username"`
	FullName  *string `json:"fullName,omitempty"`
	Bio       *string `json:"bio,omitempty"`
	Posts     []*Post `json:"posts"`
	Followers []*User `json:"followers"`
	Following []*User `json:"following"`
}
