package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"gqlgen-orm-naive/graph"
	"gqlgen-orm-naive/graph/model"
)

// Post is the resolver for the post field.
func (r *commentResolver) Post(ctx context.Context, obj *model.Comment) (*model.Post, error) {
	// NAIVE: Called once per comment (N+1 problem!)
	var post model.Post
	if err := model.DB.Where("id = ?", obj.PostID).First(&post).Error; err != nil {
		return nil, err
	}
	return &post, nil
}

// Author is the resolver for the author field.
func (r *commentResolver) Author(ctx context.Context, obj *model.Comment) (*model.User, error) {
	// NAIVE: Called once per comment (N+1 problem!)
	var user model.User
	if err := model.DB.Where("id = ?", obj.AuthorID).First(&user).Error; err != nil {
		return nil, err
	}
	return &user, nil
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
	// NAIVE: Called once per post (N+1 problem!)
	var user model.User
	if err := model.DB.Where("id = ?", obj.AuthorID).First(&user).Error; err != nil {
		return nil, err
	}
	return &user, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post) ([]*model.Comment, error) {
	// NAIVE: Called once per post (N+1 problem!)
	var comments []*model.Comment
	if err := model.DB.Where("post_id = ?", obj.ID).Find(&comments).Error; err != nil {
		return nil, err
	}
	return comments, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	// NAIVE: Load user without relationships - causes lazy loading!
	var user model.User
	if err := model.DB.Where("id = ?", id).First(&user).Error; err != nil {
		return nil, err
	}
	return &user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int) ([]*model.User, error) {
	// NAIVE: Load users without relationships - causes lazy loading!
	var users []*model.User
	query := model.DB.Limit(*limit)
	if err := query.Find(&users).Error; err != nil {
		return nil, err
	}
	return users, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	// NAIVE: Load post without relationships - causes lazy loading!
	var post model.Post
	if err := model.DB.Where("id = ?", id).First(&post).Error; err != nil {
		return nil, err
	}
	return &post, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, limit *int) ([]*model.Post, error) {
	// NAIVE: Load posts without relationships - causes lazy loading!
	var posts []*model.Post
	query := model.DB.Limit(*limit)
	if err := query.Find(&posts).Error; err != nil {
		return nil, err
	}
	return posts, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *model.User) ([]*model.Post, error) {
	// NAIVE: Called once per user in result set (N+1 problem!)
	var posts []*model.Post
	if err := model.DB.Where("author_id = ?", obj.ID).Find(&posts).Error; err != nil {
		return nil, err
	}
	return posts, nil
}

// Comments is the resolver for the comments field.
func (r *userResolver) Comments(ctx context.Context, obj *model.User) ([]*model.Comment, error) {
	// NAIVE: Called once per user in result set (N+1 problem!)
	var comments []*model.Comment
	if err := model.DB.Where("author_id = ?", obj.ID).Find(&comments).Error; err != nil {
		return nil, err
	}
	return comments, nil
}

func (r *Resolver) Comment() graph.CommentResolver { return &commentResolver{r} }

func (r *Resolver) Post() graph.PostResolver { return &postResolver{r} }

func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type commentResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
