default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 8).to_i %>
  username: <%= ENV['DB_USER'] || 'benchmark' %>
  password: <%= ENV['DB_PASSWORD'] || 'benchmark123' %>
  host: <%= ENV['DB_HOST'] || 'postgres' %>
  port: <%= ENV['DB_PORT'] || 5434 %>
  checkout_timeout: 5
  reaping_frequency: 10
  dead_connection_timeout: 5

development:
  <<: *default
  database: fraiseql_benchmark

test:
  <<: *default
  database: fraiseql_benchmark_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'fraiseql_benchmark' %>
