#!/bin/bash

echo "════════════════════════════════════════════════════════════════"
echo "Code Quality Configuration Report"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "📦 TypeScript/Node.js Frameworks"
echo "  • frameworks/express-rest"
echo "    - Tools: ESLint, Prettier, TypeScript"
echo "    - Config: .eslintrc.json, .prettierrc"
echo "  • frameworks/apollo-server"
echo "    - Tools: ESLint, Prettier, TypeScript"
echo "    - Config: .eslintrc.json, .prettierrc"
echo ""

echo "🐍 Python Frameworks"
echo "  • frameworks/fastapi-rest"
echo "    - Tools: Ruff, MyPy"
echo "    - Config: pyproject.toml (root)"
echo "  • frameworks/flask-rest"
echo "    - Tools: Ruff, MyPy"
echo "    - Config: pyproject.toml (root)"
echo "  • frameworks/strawberry"
echo "    - Tools: Ruff, MyPy"
echo "    - Config: pyproject.toml (root)"
echo "  • frameworks/graphene"
echo "    - Tools: Ruff, MyPy"
echo "    - Config: pyproject.toml (root)"
echo "  • frameworks/fraiseql"
echo "    - Tools: Ruff, MyPy"
echo "    - Config: pyproject.toml (root)"
echo ""

echo "🦀 Rust Frameworks"
echo "  • frameworks/actix-web-rest"
echo "    - Tools: Clippy, rustfmt"
echo "    - Config: Cargo.toml, .cargo/"
echo ""

echo "🐹 Go Frameworks"
echo "  • frameworks/gin-rest"
echo "    - Tools: gofmt, golangci-lint (if installed)"
echo "    - Config: .golangci.yml (recommended)"
echo "  • frameworks/go-gqlgen"
echo "    - Tools: gofmt, golangci-lint (if installed)"
echo "    - Config: .golangci.yml (recommended)"
echo ""

echo "🔧 Root-level Quality Scripts"
echo "  • scripts/check-quality.sh    - Run all quality checks"
echo "  • scripts/fix-quality.sh      - Fix code quality issues"
echo "  • scripts/lint-typescript.sh  - Check TypeScript code"
echo "  • scripts/lint-python.sh      - Check Python code"
echo "  • scripts/lint-rust.sh        - Check Rust code"
echo "  • scripts/lint-go.sh          - Check Go code"
echo "  • scripts/quality-report.sh   - Display this report"
echo ""

echo "📋 Configuration Files"
echo "  • pyproject.toml - Python linting & type checking config"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "✓ Configuration setup complete!"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. npm install in TypeScript frameworks"
echo "  2. pip install -r requirements-dev.txt in Python frameworks"
echo "  3. Run: bash scripts/check-quality.sh"
echo ""
